# Generated by Django 2.0.1 on 2018-02-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название валюты')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Курс в долларах')),
                ('last_updated', models.IntegerField(verbose_name='Последние обновление')),
            ],
        ),
    ]
