# Generated by Django 2.0.2 on 2018-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Курс в долларах'),
        ),
    ]
