# Generated by Django 2.0.2 on 2018-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0002_auto_20180208_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название валюты'),
        ),
    ]
