# Generated by Django 2.0.2 on 2018-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0003_auto_20180208_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='last_updated',
            field=models.DateTimeField(verbose_name='Последние обновление'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Курс в долларах'),
        ),
    ]
