# Generated by Django 2.0.2 on 2018-02-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0004_auto_20180209_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='last_updated',
            field=models.IntegerField(verbose_name='Последние обновление'),
        ),
    ]
