# Generated by Django 2.0.2 on 2018-02-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0005_auto_20180209_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='last_updated',
            field=models.DateTimeField(verbose_name='Последние обновление'),
        ),
    ]
